# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Confluence < Formula
  desc "Confluence CLI — fetch and manage pages"
  homepage "https://github.com/coreycoburn/cli-forge"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.1/confluence_darwin_amd64.tar.gz"
      sha256 "0e802ef7011d101bbe3d43197f2427a88f432866fb64501ce44896f4eb23027a"

      define_method(:install) do
        bin.install "confluence"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.1/confluence_darwin_arm64.tar.gz"
      sha256 "0b70a27c3a36e01c32fe0a96898e29037a92b3c601c74de2d3bde1904780c3ef"

      define_method(:install) do
        bin.install "confluence"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.1/confluence_linux_amd64.tar.gz"
      sha256 "3fd0de4d772716a9305cfe84e36a770e4714b4ae111734b8cb7f78952ce8ed00"
      define_method(:install) do
        bin.install "confluence"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.1/confluence_linux_arm64.tar.gz"
      sha256 "306b757afce59772c20949bfe2ba2b91146c97ac67cebff87cc6e89a39ac3cef"
      define_method(:install) do
        bin.install "confluence"
      end
    end
  end
end
