# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Confluence < Formula
  desc "Confluence CLI — fetch and manage pages"
  homepage "https://github.com/coreycoburn/cli-forge"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.3/confluence_darwin_amd64.tar.gz"
      sha256 "a8db6ca7ee12ded1b5658693def1e5f073c47b7bd8f7e5163b8abd2490632f83"

      define_method(:install) do
        bin.install "confluence"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.3/confluence_darwin_arm64.tar.gz"
      sha256 "c8993fdd98467c4efdc4a7c7cd1dfd04080d5aa2fdf0baf22a124f8a23324652"

      define_method(:install) do
        bin.install "confluence"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.3/confluence_linux_amd64.tar.gz"
      sha256 "00df356287e7a004bd8704b36e27d515c94e64f28790882022c656234729d853"
      define_method(:install) do
        bin.install "confluence"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.3/confluence_linux_arm64.tar.gz"
      sha256 "f229aa4e85653fe7bfa986a4721a6747a62149facd4d4aae54d5f41c899d17c0"
      define_method(:install) do
        bin.install "confluence"
      end
    end
  end
end
