# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Confluence < Formula
  desc "Confluence CLI — fetch and manage pages"
  homepage "https://github.com/coreycoburn/cli-forge"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.0/confluence_darwin_amd64.tar.gz"
      sha256 "1b8a4e0ecd47bf9f900eb67fbd188cdd7c1e3315b38ac16a3a3cf4df3db2ec29"

      define_method(:install) do
        bin.install "confluence"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.0/confluence_darwin_arm64.tar.gz"
      sha256 "5cca2eb4e7e34bebacf1836b0905a75795e64727472ca8842225e93d1c592fd1"

      define_method(:install) do
        bin.install "confluence"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.0/confluence_linux_amd64.tar.gz"
      sha256 "2bfacfafd41b254fef16adbbd8f8ec360373897bc1a629abfabc006798a50b97"
      define_method(:install) do
        bin.install "confluence"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.0/confluence_linux_arm64.tar.gz"
      sha256 "68cdcead39e057b3a9ea646722ff1453fba49e852a9474dec11ac4113c32c0dd"
      define_method(:install) do
        bin.install "confluence"
      end
    end
  end
end
