# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Example < Formula
  desc "An example CLI built with cli-forge"
  homepage "https://github.com/coreycoburn/cli-forge"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.1.0/example_darwin_amd64.tar.gz"
      sha256 "6bbfb7d3a706cfc59745cfb3c411a0e3705a898b01d8bdac467d0215116e345d"

      define_method(:install) do
        bin.install "example"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.1.0/example_darwin_arm64.tar.gz"
      sha256 "39b1af59f455ab57ace6ec709c0d944a4d1abd3d7c7258278d1efb958664098d"

      define_method(:install) do
        bin.install "example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.1.0/example_linux_amd64.tar.gz"
      sha256 "50f3cf513bf1e9587f336caeb215132f29f297039cb328b32b4a211200cc131d"
      define_method(:install) do
        bin.install "example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.1.0/example_linux_arm64.tar.gz"
      sha256 "c0fd93f166a795636068089977b6d800109d6c3de091cc143ba80dff3c5f2a6f"
      define_method(:install) do
        bin.install "example"
      end
    end
  end
end
