# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Example < Formula
  desc "An example CLI built with cli-forge"
  homepage "https://github.com/coreycoburn/cli-forge"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.2.1/example_darwin_amd64.tar.gz"
      sha256 "201cbba75e34606ccc2f9c1b57e457a84ac48b94a6f6b9d56cbba69bc42277a9"

      define_method(:install) do
        bin.install "example"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.2.1/example_darwin_arm64.tar.gz"
      sha256 "529b309c5e4efe0021fb48c537a4918ddfa76dfa64eed8dac5cfe3cd6a66dc3c"

      define_method(:install) do
        bin.install "example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.2.1/example_linux_amd64.tar.gz"
      sha256 "9644a630429517a4bbf8f2e91e01573b056029d7372e9f2eb74dee5e5e813ce4"
      define_method(:install) do
        bin.install "example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.2.1/example_linux_arm64.tar.gz"
      sha256 "8a0e955bcf4c659cb687afe873051175a78bfd4fbf8e07c081871483ebb4164e"
      define_method(:install) do
        bin.install "example"
      end
    end
  end
end
