# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Example < Formula
  desc "An example CLI built with cli-forge"
  homepage "https://github.com/coreycoburn/cli-forge"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.2.0/example_darwin_amd64.tar.gz"
      sha256 "6e80d18cfdcdc99921ec6b8870abc49f284020a31750af8deb05a373ba0809d5"

      define_method(:install) do
        bin.install "example"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.2.0/example_darwin_arm64.tar.gz"
      sha256 "7f2f84386782f8493751a245db202a7ea96a68e369a50c15819a15f59a9a7922"

      define_method(:install) do
        bin.install "example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.2.0/example_linux_amd64.tar.gz"
      sha256 "e700912765da0bb208dbcc764b36be8842f3d04743d10d2d25bb9135e8fd9526"
      define_method(:install) do
        bin.install "example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.2.0/example_linux_arm64.tar.gz"
      sha256 "d2a687a82a42b1a72aed50fe92b6c37d6ebddb5289819b66df5d4e5d6201acbd"
      define_method(:install) do
        bin.install "example"
      end
    end
  end
end
