# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kit < Formula
  desc "Design asset toolkit — convert and optimize files"
  homepage "https://github.com/coreycoburn/cli-forge"
  version "0.3.0"
  license "MIT"

  depends_on "ghostscript"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.0/kit_darwin_amd64.tar.gz"
      sha256 "71a2d49b7470025934446e114f2a9fbf3efaa4d9646b2c900a961d64b12d63a1"

      define_method(:install) do
        bin.install "kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.0/kit_darwin_arm64.tar.gz"
      sha256 "955f19b5eee12041d8b0ab768c078cae089ab051362036aebcc89e3035a22583"

      define_method(:install) do
        bin.install "kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.0/kit_linux_amd64.tar.gz"
      sha256 "8d9f0fa056b889d9df312fea9c013d9b7e781ae2512a331d493cf34f2c5b5617"
      define_method(:install) do
        bin.install "kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.0/kit_linux_arm64.tar.gz"
      sha256 "f87d432c19a92b1bc3aed727b5e53746eef64b47e5920eeb79cfcc605e3a281a"
      define_method(:install) do
        bin.install "kit"
      end
    end
  end

  def caveats
    <<~EOS
      The convert command also requires Inkscape:
        brew install --cask inkscape
    EOS
  end
end
