# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kit < Formula
  desc "Design asset toolkit — convert and optimize files"
  homepage "https://github.com/coreycoburn/cli-forge"
  version "0.3.1"
  license "MIT"

  depends_on "ghostscript"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.1/kit_darwin_amd64.tar.gz"
      sha256 "d2bfa2d2034ee9ad8c9f94b6c6d60af8cdbbebb4a2ab53168e1b17b92d34e0ec"

      define_method(:install) do
        bin.install "kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.1/kit_darwin_arm64.tar.gz"
      sha256 "d030c41e9a3003ab5eba3a58c3b4d6249871823610ea32706a7acd9ed84dc58e"

      define_method(:install) do
        bin.install "kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.1/kit_linux_amd64.tar.gz"
      sha256 "176329c0529a61756317eff70d6a540be3cacc256d02b68325e1654289b6ff0e"
      define_method(:install) do
        bin.install "kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.1/kit_linux_arm64.tar.gz"
      sha256 "c21073699da1a7ba0da25fcd3f220bd443ccce85fb1db00bfafa1e5d63dac9aa"
      define_method(:install) do
        bin.install "kit"
      end
    end
  end

  def caveats
    <<~EOS
      The convert command also requires Inkscape:
        brew install --cask inkscape
    EOS
  end
end
