# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kit < Formula
  desc "Design asset toolkit — convert and optimize files"
  homepage "https://github.com/coreycoburn/cli-forge"
  version "0.3.3"
  license "MIT"

  depends_on "ghostscript"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.3/kit_darwin_amd64.tar.gz"
      sha256 "2b1b58576ac6a4ff20b5e06c76e1cc3dc19898505be3783342e4c651bcb22e58"

      define_method(:install) do
        bin.install "kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.3/kit_darwin_arm64.tar.gz"
      sha256 "b6872ad963b9764166bc189313512609699c2db5952a65f64aa052c5f0bbf4f7"

      define_method(:install) do
        bin.install "kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.3/kit_linux_amd64.tar.gz"
      sha256 "4359e9101879323b00625882aaabbfce7a008357d01505dd932c06a33e10df0c"
      define_method(:install) do
        bin.install "kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreycoburn/cli-forge/releases/download/v0.3.3/kit_linux_arm64.tar.gz"
      sha256 "7137650da20b62b65b15ad35640d5b42ef5794e0c59ff33ce492db0817520c43"
      define_method(:install) do
        bin.install "kit"
      end
    end
  end

  def caveats
    <<~EOS
      The convert command also requires Inkscape:
        brew install --cask inkscape
    EOS
  end
end
